FROM cassandra:latest

## ENV LANG C.UTF-8

COPY ./temporal_db.cql /docker-entrypoint-initdb.d/
COPY ./datos.csv ./docker-entrypoint-initdb.d/
##COPY entrypoint.sh /

## ENTRYPOINT ["/entrypoint.sh"]d
CMD ["cassandra", "-f"]

## CMD ["cqlsh", "-f", "uni_dispositivos.cql "]