FROM cassandra:latest

RUN apt-get update && apt-get -y install vim
RUN apt-get update && apt-get -y install sudo


COPY ./meter_historial.cql /docker-entrypoint-initdb.d/
#COPY ./cassandra-sec.sh /docker-entrypoint-initdb.d/
#RUN /docker-entrypoint-initdb.d/cassandra-sec.sh
##COPY entrypoint.sh /

## ENTRYPOINT ["/entrypoint.sh"]d
CMD ["cassandra", "-f"]

## CMD ["cqlsh", "-f", "uni_dispositivos.cql "]