# Use the official Node.js 14 image as a base
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Install express and cors packages
RUN npm install express cors

# Copy the rest of the application code to the working directory
COPY /index.js .
COPY /public ./public

# Expose port 3000 to the outside world
EXPOSE 80

# Command to run the application
CMD ["node", "index.js"]
